### ISSUE TITLE
TODOS

### ISSUE THREAD

**Issue by srinortner** [srinortner/GameDesignSS2022#1]
- [x] würfel random in gegebenem bereich spawnen
- [x] plattformen größer
- [x] plattformen für jede farbe
- [x] wände höher und aus glas
- [ ] Gebäude rund um Glaskasten
- [ ] Außen Dunkel
- [ ] Licht geht an

**Comment by Viktoria-1** [comment]
Idee für skybox: https://assetstore.unity.com/packages/2d/textures-materials/sky/10-skyboxes-pack-day-night-32236
Ideen für city assests:
- low poly cartoonish style https://assetstore.unity.com/packages/3d/environments/urban/low-poly-city-from-viuletti-132536#description
- eintönige atmosphäre https://assetstore.unity.com/packages/3d/environments/urban/city-voxel-pack-136141#content
-  toony style https://assetstore.unity.com/packages/3d/environments/urban/toony-tiny-city-demo-176087
